packages:
  - wicket/
  - wicket/**
  - components/**
  - packages/*
  - proprietary/*

autoInstallPeers: false

engineStrict: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@nl-design-system/*'
  - '@nl-design-system-candidate/*'
  - '@nl-design-system-community/*'
  - '@nl-design-system-unstable/*'

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  tmp@<=0.2.3: '>=0.2.4'

saveExact: true

savePrefix: ''

strictPeerDependencies: false
