packages:
  - rotterdam-nlds-parent-wicket/
  - rotterdam-nlds-parent-wicket/**
  - components/**
  - packages/*
  - packages/web-components/*
  - proprietary/*

autoInstallPeers: false

engineStrict: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "@amsterdam/*"
  - "@gemeente-denhaag/*"
  - "@gemeente-rotterdam/*"
  - "@nl-design-system/*"
  - "@nl-design-system-candidate/*"
  - "@nl-design-system-community/*"
  - "@nl-design-system-unstable/*"
  - "@nl-rvo/*"
  - "@rijkshuisstijl-community/*"
  - "@utrecht/*"

overrides:
  esbuild@<=0.24.2: ">=0.25.0"
  handlebars@>=4.0.0 <4.7.9: ">=4.7.9"
  postcss@<7.0.36: ">=7.0.36"
  postcss@<8.4.31: ">=8.4.31"
  tmp@<=0.2.3: ">=0.2.4"

saveExact: true
savePrefix: ""

strictPeerDependencies: false
